-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 12:36:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BookStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BookStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BookStore` DEFAULT CHARACTER SET utf8 ;
USE `BookStore` ;

-- -----------------------------------------------------
-- Table `BookStore`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`genre` (
  `idgenre` INT UNSIGNED NOT NULL,
  `genre_name` NVARCHAR(50) NOT NULL,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`author` (
  `idauthor` INT UNSIGNED NOT NULL,
  `name` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`idauthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`publisher` (
  `idpublisher` INT UNSIGNED NOT NULL,
  `name` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpublisher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`supplier` (
  `idsupplier` INT UNSIGNED NOT NULL,
  `supplier_name` NVARCHAR(45) NOT NULL,
  `email` NVARCHAR(45) NOT NULL,
  `address` NVARCHAR(200) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idsupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`book` (
  `idbook` INT UNSIGNED NOT NULL,
  `name` NVARCHAR(45) NOT NULL,
  `genreID` INT UNSIGNED NOT NULL,
  `authorID` INT UNSIGNED NOT NULL,
  `publisherID` INT UNSIGNED NOT NULL,
  `supplierID` INT UNSIGNED NOT NULL,
  `selling_price` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idbook`),
  INDEX `genreID` (`genreID` ASC) VISIBLE,
  INDEX `fk_author_book_idx` (`authorID` ASC) VISIBLE,
  INDEX `fk_publisher_book_idx` (`publisherID` ASC) VISIBLE,
  INDEX `fk_supplier_book_idx` (`supplierID` ASC) VISIBLE,
  CONSTRAINT `fk_genre_book`
    FOREIGN KEY (`genreID`)
    REFERENCES `BookStore`.`genre` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_author_book`
    FOREIGN KEY (`authorID`)
    REFERENCES `BookStore`.`author` (`idauthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publisher_book`
    FOREIGN KEY (`publisherID`)
    REFERENCES `BookStore`.`publisher` (`idpublisher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_book`
    FOREIGN KEY (`supplierID`)
    REFERENCES `BookStore`.`supplier` (`idsupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`employee` (
  `idemployee` INT UNSIGNED NOT NULL,
  `name` NVARCHAR(45) NOT NULL,
  `iduser` INT UNSIGNED NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  `salary` INT NOT NULL,
  `address` NVARCHAR(200) NOT NULL,
  `hired_day` DATE NOT NULL,
  PRIMARY KEY (`idemployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`import`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`import` (
  `idimport` INT UNSIGNED NOT NULL,
  `supplierID` INT UNSIGNED NOT NULL,
  `employeeID` INT UNSIGNED NOT NULL,
  `total_payment` INT NOT NULL,
  `created_day` DATE NOT NULL,
  `modified_day` DATE NOT NULL,
  PRIMARY KEY (`idimport`),
  INDEX `fk_supplier_import_idx` (`supplierID` ASC) VISIBLE,
  INDEX `fk_employee_import_idx` (`employeeID` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_import`
    FOREIGN KEY (`supplierID`)
    REFERENCES `BookStore`.`supplier` (`idsupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_import`
    FOREIGN KEY (`employeeID`)
    REFERENCES `BookStore`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`import_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`import_item` (
  `idimport` INT UNSIGNED NOT NULL,
  `idbook` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `basic_price` INT UNSIGNED NOT NULL,
  `modified_day` DATE NOT NULL,
  PRIMARY KEY (`idimport`, `idbook`),
  INDEX `fk_import_book_idx` (`idbook` ASC) VISIBLE,
  CONSTRAINT `fk_import_book`
    FOREIGN KEY (`idbook`)
    REFERENCES `BookStore`.`book` (`idbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_import`
    FOREIGN KEY (`idimport`)
    REFERENCES `BookStore`.`import` (`idimport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`customer` (
  `idcustomer` INT UNSIGNED NOT NULL,
  `name` NVARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idcustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`order` (
  `idorder` INT UNSIGNED NOT NULL,
  `employeeID` INT UNSIGNED NOT NULL,
  `customerID` INT UNSIGNED NOT NULL,
  `total_payment` INT NOT NULL,
  `created_day` DATE NOT NULL,
  `modified_day` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `fk_order_customer_idx` (`customerID` ASC) VISIBLE,
  INDEX `fk_order_employee_idx` (`employeeID` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer`
    FOREIGN KEY (`customerID`)
    REFERENCES `BookStore`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_employee`
    FOREIGN KEY (`employeeID`)
    REFERENCES `BookStore`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`order_item` (
  `idorder` INT UNSIGNED NOT NULL,
  `idbook` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `selling_price` INT UNSIGNED NOT NULL,
  `modified_day` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorder`, `idbook`),
  INDEX `fk_book_order_idx` (`idbook` ASC) VISIBLE,
  CONSTRAINT `fk_order`
    FOREIGN KEY (`idorder`)
    REFERENCES `BookStore`.`order` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_order`
    FOREIGN KEY (`idbook`)
    REFERENCES `BookStore`.`book` (`idbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB; 


-- -----------------------------------------------------
-- Table `BookStore`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`user` (
  `iduser` INT NOT NULL,
  `username` NVARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created_day` DATE NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; 
